/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeria;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.time.LocalTime;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author rous2
 */
public class Servidor extends javax.swing.JFrame {

    static LocalTime horaActual = LocalTime.now();
    int contI=0, contV=0, contA=0;
    static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static FileInputStream fi;
    static DataOutputStream dout;
    static FileOutputStream fo;

    public Servidor() {
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        Enviar = new javax.swing.JButton();
        Multimedia = new javax.swing.JButton();
        Msg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial = new javax.swing.JTextArea();
        Imagenes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajeria/Icon/enviar.png"))); // NOI18N
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        Multimedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mensajeria/Icon/adjunto (1).png"))); // NOI18N
        Multimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultimediaActionPerformed(evt);
            }
        });

        Msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsgActionPerformed(evt);
            }
        });

        Historial.setColumns(20);
        Historial.setRows(5);
        jScrollPane1.setViewportView(Historial);

        Imagenes.setText("Imagenes");
        Imagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagenesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Msg, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(Multimedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Imagenes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imagenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multimedia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultimediaActionPerformed

        File ruta;
        String rutas;
        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);
        FileNameExtensionFilter filt = new FileNameExtensionFilter("JPG, MP4, MP3", "jpg", "mp4", "mp3");
        jf.setFileFilter(filt);
        int res = jf.showOpenDialog(this);

        if (res == JFileChooser.APPROVE_OPTION) {
            ruta = jf.getSelectedFile();
            rutas = ruta.getPath();

            String ex = getFileExtension(ruta);
            if(ex.equals("jpg")){
                contI++;
                rsdragdropfiles.RSDragDropFiles.setCopiar(rutas, "src/Img/"+contI+"."+ex);
            }else if(ex.equals("mp4")){
                contV++;
                rsdragdropfiles.RSDragDropFiles.setCopiar(rutas, "src/Vid/"+contV+"."+ex);
            }else if(ex.equals("mp3")){
                contA++;
                rsdragdropfiles.RSDragDropFiles.setCopiar(rutas, "src/Aud/"+contA+"."+ex);
            }

            try {
                String msg = "";
                msg = Msg.getText().trim();
                int hora = horaActual.getHour();
                int minutos = horaActual.getMinute();
                Historial.setText(Historial.getText().trim() + "\n\n Server "+hora+":"+minutos+": Nueva archivo");
               
                dout.writeUTF(msg);
                Msg.setText("");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_MultimediaActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed

        try {
            String msg = "";
            msg = Msg.getText().trim();
            int hora = horaActual.getHour();
            int minutos = horaActual.getMinute();
            Historial.setText(Historial.getText().trim() + "\n\n Server\t" + hora+":"+minutos+"\n"+msg);
           
            dout.writeUTF(msg);
            Msg.setText("");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EnviarActionPerformed

    private void MsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MsgActionPerformed

    private void ImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenesActionPerformed
        contI = (int)num();
        if(contI==-1){
            
        }else{
            Imagenes img = new Imagenes();
            img.setSize(360,310);
            img.setLocationRelativeTo(null);
            img.setVisible(true);
        }
    }//GEN-LAST:event_ImagenesActionPerformed

    public long num(){
        Path carpeta = Paths.get("src/Img");
        long cantidadArchivos = -1;
        if (Files.isDirectory(carpeta)) {
            try {
                 cantidadArchivos = Files.walk(carpeta, 1)
                    .filter(p -> !p.equals(carpeta))
                    .count();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return cantidadArchivos;
        } else {
            return -1;
        }
    }
    
    private static String getFileExtension(File file) {
        String fileName = file.getName();
        int lastIndex = fileName.lastIndexOf('.');
        if (lastIndex >= 0 && lastIndex < fileName.length() - 1) {
            return fileName.substring(lastIndex + 1);
        }
        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });

        String msgin = "";
        try {
            ss = new ServerSocket(1201);
            s = ss.accept();
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            while (!msgin.equals("Salir")) {
                msgin = din.readUTF();
                int hora = horaActual.getHour();
                int minutos = horaActual.getMinute();
                Historial.setText(Historial.getText().trim() + "\n\n Cliente\t" + hora+":"+minutos+"\n"+msgin);
                
            }

        } catch (Exception e) {
        }

    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private static javax.swing.JTextArea Historial;
    private javax.swing.JButton Imagenes;
    private javax.swing.JTextField Msg;
    private javax.swing.JButton Multimedia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
